### ISSUE TITLE
Question regarding the "Bi-affine Pairwise Scores"

### ISSUE THREAD

**Issue by arwhirang** [patverga/bran#1]
Hello?

I read the paper and I found the "Bi-affine Pairwise Scores" concept interesting. However, in your code, it doesn't seem to use the "Bi-affine Pairwise Scores" equation described in the paper. 
I think the base classifier class, "ClassifierModel" in the classifier_models.py do not have this "Bi-affine Pairwise Scores" feature.
If I am mistaken, could you tell me where to look?

**Comment by patverga** [comment]
Hi

The bi-affine pairwise scores are being calculated here: https://github.com/patverga/bran/blob/master/src/models/transformer.py#L466
